name: Build Container
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build .#container
